import { SPLIT_TYPES } from "./enums";
import { FB_SPLIT_PROGRAMMING } from "./fb";
import {
  FOUR_DAY_SPLIT_PROGRAMMING,
  FOUR_DAY_SPLIT_PROGRAMMING_LABELS,
} from "./four_day";
import {
  THREE_DAY_SPLIT_PROGRAMMING,
  THREE_DAY_SPLIT_PROGRAMMING_LABELS,
} from "./three_day";
import {
  TWO_DAY_SPLIT_PROGRAMMING,
  TWO_DAY_SPLIT_PROGRAMMING_LABELS,
} from "./two_day";

export const SPLIT_TYPE_PROGRAMMING_MAP = {
  [SPLIT_TYPES.FB]: FB_SPLIT_PROGRAMMING,
  [SPLIT_TYPES.TWO_DAY]: TWO_DAY_SPLIT_PROGRAMMING,
  [SPLIT_TYPES.THREE_DAY]: THREE_DAY_SPLIT_PROGRAMMING,
  [SPLIT_TYPES.FOUR_DAY]: FOUR_DAY_SPLIT_PROGRAMMING,
};

export const SPLIT_TYPE_PROGRAMMING_LABEL_MAP = {
  [SPLIT_TYPES.TWO_DAY]: TWO_DAY_SPLIT_PROGRAMMING_LABELS,
  [SPLIT_TYPES.THREE_DAY]: THREE_DAY_SPLIT_PROGRAMMING_LABELS,
  [SPLIT_TYPES.FOUR_DAY]: FOUR_DAY_SPLIT_PROGRAMMING_LABELS,
};
