name: Migrate Database - Production 
on:
  push:
    paths:
      - packages/database/prisma/migrations/** 
    branches:
      - main
  workflow_dispatch: 


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod-cybersplit
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: yarn install
      - name: Apply all pending migrations to the database
        run: yarn db:migrate:deploy 
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}